apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ai-analyzer
  name: ai-analyzer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-analyzer
  template:
    metadata:
      labels:
        app: ai-analyzer
    spec:
      containers:
      - image: deadvexon/ai-analyzer-find-your-bias:3f24b0ce9247604b9f54bec67d9361d30ea194bb
        name: ai-analyzer
        env:
        - name: AWS_REGION
          value: "us-east-1" 
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-credentials 
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-credentials 
              key: AWS_SECRET_ACCESS_KEY
        ports:
        - containerPort: 5001
          name: ai-analyzer
        livenessProbe:
          httpGet:
            path: /health
            port: 5001
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /health
            port: 5001
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "200m"
            memory: "512Mi"